# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simply_stored_scaffold}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Vincenzo Rivello"]
  s.date = %q{2010-08-02}
  s.description = %q{A simple scaffold generator for Couchrest + couch_potato + simply_stored combo interface for Rails to CouchDB}
  s.email = %q{vincenzo.rivello@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "rails_generators/simply_stored_scaffold/USAGE",
     "rails_generators/simply_stored_scaffold/simply_stored_scaffold_generator.rb",
     "rails_generators/simply_stored_scaffold/templates/controller.rb",
     "rails_generators/simply_stored_scaffold/templates/helper.rb",
     "rails_generators/simply_stored_scaffold/templates/model.rb",
     "rails_generators/simply_stored_scaffold/templates/views/_form.html.erb",
     "rails_generators/simply_stored_scaffold/templates/views/edit.html.erb",
     "rails_generators/simply_stored_scaffold/templates/views/index.html.erb",
     "rails_generators/simply_stored_scaffold/templates/views/new.html.erb",
     "rails_generators/simply_stored_scaffold/templates/views/show.html.erb"
  ]
  s.homepage = %q{http://github.com/enzor/simply_stored_scaffold}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A simple scaffold generator for simply_stored}
  s.test_files = [
    "features/simply_stored_scaffold.feature",
     "features/step_definitions",
     "features/step_definitions/common_steps.rb",
     "features/step_definitions/rails_setup_steps.rb",
     "features/support",
     "features/support/env.rb",
     "features/support/matchers.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<couchrest>, [">= 0.37"])
      s.add_runtime_dependency(%q<couch_potato>, [">= 0.3.0"])
      s.add_runtime_dependency(%q<simply_stored>, [">= 0.3.6"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<couchrest>, [">= 0.37"])
      s.add_dependency(%q<couch_potato>, [">= 0.3.0"])
      s.add_dependency(%q<simply_stored>, [">= 0.3.6"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<couchrest>, [">= 0.37"])
    s.add_dependency(%q<couch_potato>, [">= 0.3.0"])
    s.add_dependency(%q<simply_stored>, [">= 0.3.6"])
  end
end

